---
name: ansible-lint
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip3 install yamllint

      - name: Run yamllint.
        run: yamllint .

      - name: Run ansible-lint.
        uses: ansible/ansible-lint@main
